"use client";
import { useEffect, useState } from "react";
import { Navbar } from "@/components/Navbar";
import { type WeekSchedule as WeekScheduleType } from "@/types/scheduleTypes";
import SavedPlan from "@/components/saved-plans/SavedPlan";
import DeletePlan from "@/components/ui/DeletePlan";

// Dummy Schedule #1: Remove as necessary
// Be sure to update when the WeekSchedule component changes!
const dummySchedule: WeekScheduleType = {
  Monday: [
    {
      classTitle: "CSCI 3030",
      className: "Computing, Ethics, and Society",
      description:
        "Introduction to social and ethical issues relating to computer science and information technology. Topics include privacy, intellectual property, open-source software, the digital divide, globalization, professional ethics, social justice issues, and current events. Students should have a working knowledge of personal computing.",
      locationLong: "Boyd Research and Education Center 100",
      locationShort: "Boyd 100",
      prereq: "ENGL 1102",
      coreq: "",
      professor: "John Doe",
      semester: "Spring",
      timeStart: "8:00 am",
      timeEnd: "8:50 am",
      timeDifference: null,
      credits: 3,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "MW",
      otherTimes: ["F", "8:00 am - 8:50 am", "Chemistry 100"],
    },

    {
      classTitle: "CSCI 1302",
      className: "Software Development",
      description: "The course description will be displayed here.",
      locationLong: "Conner Hall 100",
      locationShort: "Conner 100",
      prereq: "ENGL 1102",
      coreq: "",
      professor: "John Doe",
      semester: "All",
      timeStart: "10:20 am",
      timeEnd: "11:10 am",
      timeDifference: null,
      credits: 4,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "M",
      otherTimes: ["TR", "9:35 am - 10:50 am", "Food Sci 100"],
    },

    {
      classTitle: "BIOL 1103",
      className: "Topics in Biology",
      description: "The course description will be displayed here.",
      locationLong: "Science Learning Center 100",
      locationShort: "SLC 100",
      prereq: "",
      coreq: "BIOL 1103L",
      professor: "Jane Doe",
      semester: "Spring/Fall",
      timeStart: "1:30 pm",
      timeEnd: "2:20 pm",
      timeDifference: null,
      credits: 3,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-dev-dog-blue",
      borderColor: "border-dev-dog-blue",

      currentDay: "MWF",
      otherTimes: ["", "", ""],
    },
  ],

  Tuesday: [
    {
      classTitle: "CSCI 1302",
      className: "Software Development",
      description: "The course description will be displayed here.",
      locationLong: "Food Science 100",
      locationShort: "Food Sci 100",
      prereq: "ENGL 1102",
      coreq: "",
      professor: "John Doe",
      semester: "All",
      timeStart: "9:35 am",
      timeEnd: "10:50 am",
      timeDifference: null,
      credits: 4,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "TR",
      otherTimes: ["M", "10:20 am - 11:10 am", "Conner 100"],
    },

    {
      classTitle: "MUSI 2300",
      className: "Music in Athens",
      description:
        "Explores national and international musical and cultural trends. The course draws from Athens, Georgia’s diverse musical communities and their histories, exploring the rock, hip hop, and indie popular music scenes along with African-American traditions, folk and traditional musics, and the emergent Latin music scene.",
      locationLong: "Hugh Hudgson School of Music 100",
      locationShort: "Hugh Hudgson 100",
      prereq: "",
      coreq: "",
      professor: "Jane Doe",
      semester: "Spring",
      timeStart: "12:45 pm",
      timeEnd: "2:00 pm",
      timeDifference: null,
      credits: 3,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-lake-herrick",
      borderColor: "border-lake-herrick",
      currentDay: "TR",
      otherTimes: ["", "", ""],
    },
  ],

  Wednesday: [
    {
      classTitle: "CSCI 3030",
      className: "Computing, Ethics, and Society",
      description: "The course description will be displayed here.",
      locationLong: "Boyd Research and Education Center 100",
      locationShort: "Boyd 100",
      prereq: "ENGL 1102",
      coreq: "",
      professor: "John Doe",
      semester: "Spring",
      timeStart: "8:00 am",
      timeEnd: "8:50 am",
      timeDifference: null,
      credits: 3,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "MW",
      otherTimes: ["F", "8:00 am - 8:50 am", "Chemistry 100"],
    },

    {
      classTitle: "BIOL 1103",
      className: "Topics in Biology",
      description: "The course description will be displayed here.",
      locationLong: "Science Learning Center 100",
      locationShort: "SLC 100",
      prereq: "",
      coreq: "BIOL 1103L",
      professor: "Jane Doe",
      semester: "Spring/Fall",
      timeStart: "1:30 pm",
      timeEnd: "2:20 pm",
      timeDifference: null,
      credits: 3,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-dev-dog-blue",
      borderColor: "border-dev-dog-blue",
      currentDay: "MWF",
      otherTimes: ["", "", ""],
    },
  ],

  Thursday: [
    {
      classTitle: "CSCI 1302",
      className: "Software Development",
      description: "The course description will be displayed here.",
      locationLong: "Food Science 100",
      locationShort: "Food Sci 100",
      prereq: "ENGL 1102",
      coreq: "",
      professor: "John Doe",
      semester: "Spring",
      timeStart: "9:35 am",
      timeEnd: "10:50 am",
      timeDifference: null,
      credits: 4,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "TR",
      otherTimes: ["M", "10:20 am - 11:10 am", "Conner 100"],
    },

    {
      classTitle: "MUSI 2300",
      className: "Music in Athens",
      description: "The course description will be displayed here.",
      locationLong: "Hugh Hudgson School of Music 100",
      locationShort: "Hugh Hudgson 100",
      prereq: "ENGL 1102",
      coreq: "",
      professor: "Jane Doe",
      semester: "Spring",
      timeStart: "12:45 pm",
      timeEnd: "2:00 pm",
      timeDifference: null,
      credits: 3,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-lake-herrick",
      borderColor: "border-lake-herrick",
      currentDay: "TR",
      otherTimes: ["", "", ""],
    },

    {
      classTitle: "BIOL 1103L",
      className: "Concepts in Biology Laboratory",
      description: "The course description will be displayed here.",
      locationLong: "Science Learning Center 100",
      locationShort: "SLC 100",
      prereq: "",
      coreq: "BIOL 1103",
      professor: "Jane Doe",
      semester: "Spring/Fall",
      timeStart: "2:20 pm",
      timeEnd: "4:15 pm",
      timeDifference: null,
      credits: 1,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-dev-dog-blue",
      borderColor: "border-dev-dog-blue",
      currentDay: "R",
      otherTimes: ["", "", ""],
    },
  ],

  Friday: [
    {
      classTitle: "CSCI 3030",
      className: "Computing, Ethics, and Society",
      description: "The course description will be displayed here.",
      locationLong: "Boyd Research and Education Center 100",
      locationShort: "Chemistry 100",
      prereq: "ENGL 1102",
      coreq: "",
      professor: "John Doe",
      semester: "Spring",
      timeStart: "8:00 am",
      timeEnd: "8:50 am",
      timeDifference: null,
      credits: 3,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "F",
      otherTimes: ["MW", "8:00 - 8:50 am", "Boyd 100"],
    },

    {
      classTitle: "BIOL 1103",
      className: "Topics in Biology",
      description: "The course description will be displayed here.",
      locationLong: "Science Learning Center 100",
      locationShort: "SLC 100",
      prereq: "",
      coreq: "BIOL 1103L",
      professor: "Jane Doe",
      semester: "Spring/Fall",
      timeStart: "1:30 pm",
      timeEnd: "2:20 pm",
      timeDifference: null,
      credits: 3,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-dev-dog-blue",
      borderColor: "border-dev-dog-blue",
      currentDay: "MWF",
      otherTimes: ["", "", ""],
    },
  ],
};

// Dummy Schedule #2: Remove as necessary
// Be sure to update when the WeekSchedule component changes!
const dummySchedule2: WeekScheduleType = {
  Monday: [
    {
      classTitle: "CSCI 3030",
      className: "Computing, Ethics, and Society",
      description:
        "Introduction to social and ethical issues relating to computer science and information technology. Topics include privacy, intellectual property, open-source software, the digital divide, globalization, professional ethics, social justice issues, and current events. Students should have a working knowledge of personal computing.",
      locationLong: "Boyd Research and Education Center 100",
      locationShort: "Boyd 100",
      prereq: "ENGL 1102",
      coreq: "",
      professor: "John Doe",
      semester: "Spring",
      timeStart: "1:30 pm",
      timeEnd: "2:20 pm",
      timeDifference: null,
      credits: 3,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "MW",
      otherTimes: ["F", "8:00 am - 8:50 am", "Chemistry 100"],
    },

    {
      classTitle: "CSCI 1302",
      className: "Software Development",
      description: "The course description will be displayed here.",
      locationLong: "Conner Hall 100",
      locationShort: "Conner 100",
      prereq: "ENGL 1102",
      coreq: "",
      professor: "John Doe",
      semester: "All",
      timeStart: "10:20 am",
      timeEnd: "11:10 am",
      timeDifference: null,
      credits: 4,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "M",
      otherTimes: ["TR", "9:35 am - 10:50 am", "Food Sci 100"],
    },

    {
      classTitle: "BIOL 1103",
      className: "Topics in Biology",
      description: "The course description will be displayed here.",
      locationLong: "Science Learning Center 100",
      locationShort: "SLC 100",
      prereq: "",
      coreq: "BIOL 1103L",
      professor: "Jane Doe",
      semester: "Spring/Fall",
      timeStart: "9:10 am",
      timeEnd: "10:00 am",
      timeDifference: null,
      credits: 3,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-dev-dog-blue",
      borderColor: "border-dev-dog-blue",

      currentDay: "MWF",
      otherTimes: ["", "", ""],
    },
  ],

  Tuesday: [
    {
      classTitle: "CSCI 1302",
      className: "Software Development",
      description: "The course description will be displayed here.",
      locationLong: "Food Science 100",
      locationShort: "Food Sci 100",
      prereq: "ENGL 1102",
      coreq: "",
      professor: "John Doe",
      semester: "All",
      timeStart: "9:35 am",
      timeEnd: "10:50 am",
      timeDifference: null,
      credits: 4,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "TR",
      otherTimes: ["M", "10:20 am - 11:10 am", "Conner 100"],
    },

    {
      classTitle: "MUSI 2300",
      className: "Music in Athens",
      description:
        "Explores national and international musical and cultural trends. The course draws from Athens, Georgia’s diverse musical communities and their histories, exploring the rock, hip hop, and indie popular music scenes along with African-American traditions, folk and traditional musics, and the emergent Latin music scene.",
      locationLong: "Hugh Hudgson School of Music 100",
      locationShort: "Hugh Hudgson 100",
      prereq: "",
      coreq: "",
      professor: "Jane Doe",
      semester: "Spring",
      timeStart: "12:45 pm",
      timeEnd: "2:00 pm",
      timeDifference: null,
      credits: 3,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-lake-herrick",
      borderColor: "border-lake-herrick",
      currentDay: "TR",
      otherTimes: ["", "", ""],
    },
  ],

  Wednesday: [
    {
      classTitle: "CSCI 3030",
      className: "Computing, Ethics, and Society",
      description: "The course description will be displayed here.",
      locationLong: "Boyd Research and Education Center 100",
      locationShort: "Boyd 100",
      prereq: "ENGL 1102",
      coreq: "",
      professor: "John Doe",
      semester: "Spring",
      timeStart: "1:30 pm",
      timeEnd: "2:20 pm",
      timeDifference: null,
      credits: 3,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "MW",
      otherTimes: ["F", "1:30 pm - 2:20 pm", "Chemistry 100"],
    },

    {
      classTitle: "BIOL 1103",
      className: "Topics in Biology",
      description: "The course description will be displayed here.",
      locationLong: "Science Learning Center 100",
      locationShort: "SLC 100",
      prereq: "",
      coreq: "BIOL 1103L",
      professor: "Jane Doe",
      semester: "Spring/Fall",
      timeStart: "9:10 am",
      timeEnd: "10:00 am",
      timeDifference: null,
      credits: 3,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-dev-dog-blue",
      borderColor: "border-dev-dog-blue",
      currentDay: "MWF",
      otherTimes: ["", "", ""],
    },
  ],

  Thursday: [
    {
      classTitle: "CSCI 1302",
      className: "Software Development",
      description: "The course description will be displayed here.",
      locationLong: "Food Science 100",
      locationShort: "Food Sci 100",
      prereq: "ENGL 1102",
      coreq: "",
      professor: "John Doe",
      semester: "Spring",
      timeStart: "9:35 am",
      timeEnd: "10:50 am",
      timeDifference: null,
      credits: 4,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "TR",
      otherTimes: ["M", "10:20 am - 11:10 am", "Conner 100"],
    },

    {
      classTitle: "MUSI 2300",
      className: "Music in Athens",
      description: "The course description will be displayed here.",
      locationLong: "Hugh Hudgson School of Music 100",
      locationShort: "Hugh Hudgson 100",
      prereq: "ENGL 1102",
      coreq: "",
      professor: "Jane Doe",
      semester: "Spring",
      timeStart: "12:45 pm",
      timeEnd: "2:00 pm",
      timeDifference: null,
      credits: 3,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-lake-herrick",
      borderColor: "border-lake-herrick",
      currentDay: "TR",
      otherTimes: ["", "", ""],
    },

    {
      classTitle: "BIOL 1103L",
      className: "Concepts in Biology Laboratory",
      description: "The course description will be displayed here.",
      locationLong: "Science Learning Center 100",
      locationShort: "SLC 100",
      prereq: "",
      coreq: "BIOL 1103",
      professor: "Jane Doe",
      semester: "Spring/Fall",
      timeStart: "2:20 pm",
      timeEnd: "4:15 pm",
      timeDifference: null,
      credits: 1,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-dev-dog-blue",
      borderColor: "border-dev-dog-blue",
      currentDay: "R",
      otherTimes: ["", "", ""],
    },
  ],

  Friday: [
    {
      classTitle: "CSCI 3030",
      className: "Computing, Ethics, and Society",
      description: "The course description will be displayed here.",
      locationLong: "Boyd Research and Education Center 100",
      locationShort: "Chemistry 100",
      prereq: "ENGL 1102",
      coreq: "",
      professor: "John Doe",
      semester: "Spring",
      timeStart: "1:30 pm",
      timeEnd: "2:20 pm",
      timeDifference: null,
      credits: 3,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "F",
      otherTimes: ["MW", "1:30 pm - 2:20 pm", "Boyd 100"],
    },

    {
      classTitle: "BIOL 1103",
      className: "Topics in Biology",
      description: "The course description will be displayed here.",
      locationLong: "Science Learning Center 100",
      locationShort: "SLC 100",
      prereq: "",
      coreq: "BIOL 1103L",
      professor: "Jane Doe",
      semester: "Spring/Fall",
      timeStart: "9:10 am",
      timeEnd: "10:00 am",
      timeDifference: null,
      credits: 3,
      crn: 26510,
      openSeats: 100,
      maxSeats: 100,
      waitlist: 0,
      bgColor: "bg-dev-dog-blue",
      borderColor: "border-dev-dog-blue",
      currentDay: "MWF",
      otherTimes: ["", "", ""],
    },
  ],
};


const dummySchedule3: WeekScheduleType = {
  Monday: [
    {
      classTitle: "HIST 2001",
      className: "U.S. History to 1865",
      description:
        "A survey of major social, political, and economic developments in the United States from colonization to the end of the Civil War.",
      locationLong: "History Building 204",
      locationShort: "Hist 204",
      prereq: "",
      coreq: "",
      professor: "Dr. B. Carter",
      semester: "Fall",
      timeStart: "10:20 am",
      timeEnd: "11:10 am",
      timeDifference: null,
      credits: 3,
      crn: 30012,
      openSeats: 45,
      maxSeats: 50,
      waitlist: 0,
      bgColor: "bg-dev-dog-blue",
      borderColor: "border-dev-dog-blue",
      currentDay: "M",
      otherTimes: ["W", "10:20 am - 11:10 am", "Hist 204"],
    },
    {
      classTitle: "COMM 1010",
      className: "Public Speaking",
      description:
        "Fundamentals of effective oral communication. Emphasis on organization, delivery, and critical thinking.",
      locationLong: "Communication Building 200",
      locationShort: "Comm 200",
      prereq: "",
      coreq: "",
      professor: "Prof. K. Robinson",
      semester: "Fall",
      timeStart: "1:30 pm",
      timeEnd: "2:20 pm",
      timeDifference: null,
      credits: 3,
      crn: 30013,
      openSeats: 35,
      maxSeats: 40,
      waitlist: 0,
      bgColor: "bg-lake-herrick",
      borderColor: "border-lake-herrick",
      currentDay: "MWF",
      otherTimes: ["", "", ""],
    },
  ],

  Tuesday: [
    {
      classTitle: "MATH 1101",
      className: "Introduction to Mathematical Modeling",
      description:
        "Continuation of mathematical modeling topics with emphasis on group activities and real-world applications.",
      locationLong: "Mathematics Building 101",
      locationShort: "Math 101",
      prereq: "",
      coreq: "",
      professor: "Dr. A. Phillips",
      semester: "Fall",
      timeStart: "9:35 am",
      timeEnd: "10:50 am",
      timeDifference: null,
      credits: 3,
      crn: 30011,
      openSeats: 60,
      maxSeats: 60,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "TR",
      otherTimes: ["MW", "8:00 am - 8:50 am", "Math 101"],
    },
  ],

  Wednesday: [
    {
      classTitle: "HIST 2001",
      className: "U.S. History to 1865",
      description:
        "Explores the cultural, political, and social changes in the U.S. up to the Civil War era.",
      locationLong: "History Building 204",
      locationShort: "Hist 204",
      prereq: "",
      coreq: "",
      professor: "Dr. B. Carter",
      semester: "Fall",
      timeStart: "10:20 am",
      timeEnd: "11:10 am",
      timeDifference: null,
      credits: 3,
      crn: 30012,
      openSeats: 45,
      maxSeats: 50,
      waitlist: 0,
      bgColor: "bg-dev-dog-blue",
      borderColor: "border-dev-dog-blue",
      currentDay: "W",
      otherTimes: ["M", "10:20 am - 11:10 am", "Hist 204"],
    },
    {
      classTitle: "COMM 1010",
      className: "Public Speaking",
      description:
        "Continued practice in speech construction, persuasive speaking, and critical listening.",
      locationLong: "Communication Building 200",
      locationShort: "Comm 200",
      prereq: "",
      coreq: "",
      professor: "Prof. K. Robinson",
      semester: "Fall",
      timeStart: "1:30 pm",
      timeEnd: "2:20 pm",
      timeDifference: null,
      credits: 3,
      crn: 30013,
      openSeats: 35,
      maxSeats: 40,
      waitlist: 0,
      bgColor: "bg-lake-herrick",
      borderColor: "border-lake-herrick",
      currentDay: "MWF",
      otherTimes: ["", "", ""],
    },
  ],

  Thursday: [
    {
      classTitle: "MATH 1101",
      className: "Introduction to Mathematical Modeling",
      description:
        "Lab component focusing on practical applications of mathematical models in science and business.",
      locationLong: "Mathematics Building 101",
      locationShort: "Math 101",
      prereq: "",
      coreq: "",
      professor: "Dr. A. Phillips",
      semester: "Fall",
      timeStart: "9:35 am",
      timeEnd: "10:50 am",
      timeDifference: null,
      credits: 3,
      crn: 30011,
      openSeats: 60,
      maxSeats: 60,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "TR",
      otherTimes: ["MW", "8:00 am - 8:50 am", "Math 101"],
    },
    {
      classTitle: "COMM 1010L",
      className: "Public Speaking Lab",
      description:
        "Practical lab to refine speech writing, group communication, and presentation skills.",
      locationLong: "Communication Building 220",
      locationShort: "Comm 220",
      prereq: "COMM 1010",
      coreq: "",
      professor: "Prof. K. Robinson",
      semester: "Fall",
      timeStart: "2:20 pm",
      timeEnd: "4:15 pm",
      timeDifference: null,
      credits: 1,
      crn: 30014,
      openSeats: 20,
      maxSeats: 20,
      waitlist: 0,
      bgColor: "bg-lake-herrick",
      borderColor: "border-lake-herrick",
      currentDay: "R",
      otherTimes: ["", "", ""],
    },
  ],

  Friday: [
    {
      classTitle: "MATH 1101",
      className: "Introduction to Mathematical Modeling",
      description:
        "Continuation of lecture material with additional problem-solving sessions.",
      locationLong: "Mathematics Building 101",
      locationShort: "Math 101",
      prereq: "",
      coreq: "",
      professor: "Dr. A. Phillips",
      semester: "Fall",
      timeStart: "8:00 am",
      timeEnd: "8:50 am",
      timeDifference: null,
      credits: 3,
      crn: 30011,
      openSeats: 60,
      maxSeats: 60,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "F",
      otherTimes: ["MW", "8:00 am - 8:50 am", "Math 101"],
    },
    {
      classTitle: "HIST 2001",
      className: "U.S. History to 1865",
      description:
        "Weekly quiz and review session on major historical themes and figures.",
      locationLong: "History Building 204",
      locationShort: "Hist 204",
      prereq: "",
      coreq: "",
      professor: "Dr. B. Carter",
      semester: "Fall",
      timeStart: "1:30 pm",
      timeEnd: "2:20 pm",
      timeDifference: null,
      credits: 3,
      crn: 30012,
      openSeats: 45,
      maxSeats: 50,
      waitlist: 0,
      bgColor: "bg-dev-dog-blue",
      borderColor: "border-dev-dog-blue",
      currentDay: "F",
      otherTimes: ["MW", "10:20 am - 11:10 am", "Hist 204"],
    },
  ],
};

const dummySchedule4: WeekScheduleType = {
  Monday: [
    {
      classTitle: "BIOL 1200",
      className: "Principles of Biology",
      description:
        "Introduction to cell biology, genetics, and physiology. Emphasis on real-world applications.",
      locationLong: "Science Center 110",
      locationShort: "Sci 110",
      prereq: "",
      coreq: "",
      professor: "Dr. Leslie Park",
      semester: "Fall",
      timeStart: "9:10 am",
      timeEnd: "10:00 am",
      timeDifference: null,
      credits: 3,
      crn: 40101,
      openSeats: 40,
      maxSeats: 40,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "MW",
      otherTimes: ["MW", "9:10 am - 10:00 am", "Sci 110"],
    },
    {
      classTitle: "MATH 2250",
      className: "Calculus I",
      description:
        "Limits, derivatives, and applications of differentiation. Introduction to integrals.",
      locationLong: "Mathematics Building 210",
      locationShort: "Math 210",
      prereq: "",
      coreq: "",
      professor: "Dr. George Simons",
      semester: "Fall",
      timeStart: "11:25 am",
      timeEnd: "12:15 pm",
      timeDifference: null,
      credits: 4,
      crn: 40102,
      openSeats: 50,
      maxSeats: 50,
      waitlist: 0,
      bgColor: "bg-dev-dog-blue",
      borderColor: "border-dev-dog-blue",
      currentDay: "M",
      otherTimes: ["W", "11:25 am - 12:15 pm", "Math 210"],
    },
    {
      classTitle: "SPAN 1001",
      className: "Elementary Spanish I",
      description:
        "Basic Spanish language skills: speaking, listening, reading, and writing. Cultural contexts included.",
      locationLong: "Language Building 105",
      locationShort: "Lang 105",
      prereq: "",
      coreq: "",
      professor: "Prof. Carla Ruiz",
      semester: "Fall",
      timeStart: "3:00 pm",
      timeEnd: "3:50 pm",
      timeDifference: null,
      credits: 3,
      crn: 40103,
      openSeats: 30,
      maxSeats: 30,
      waitlist: 0,
      bgColor: "bg-lake-herrick",
      borderColor: "border-lake-herrick",
      currentDay: "MWF",
      otherTimes: ["", "", ""],
    },
  ],

  Tuesday: [
    {
      classTitle: "BIOL 1200",
      className: "Principles of Biology",
      description:
        "Extended discussion and group activities on cell structure and metabolism.",
      locationLong: "Science Center 110",
      locationShort: "Sci 110",
      prereq: "",
      coreq: "",
      professor: "Dr. Leslie Park",
      semester: "Fall",
      timeStart: "8:00 am",
      timeEnd: "9:15 am",
      timeDifference: null,
      credits: 3,
      crn: 40101,
      openSeats: 40,
      maxSeats: 40,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "TR",
      otherTimes: ["MWF", "9:10 am - 10:00 am", "Sci 110"],
    },
  ],

  Wednesday: [
    {
      classTitle: "MATH 2250",
      className: "Calculus I",
      description:
        "Continued exploration of integral calculus and the Fundamental Theorem of Calculus.",
      locationLong: "Mathematics Building 210",
      locationShort: "Math 210",
      prereq: "",
      coreq: "",
      professor: "Dr. George Simons",
      semester: "Fall",
      timeStart: "11:25 am",
      timeEnd: "12:15 pm",
      timeDifference: null,
      credits: 4,
      crn: 40102,
      openSeats: 50,
      maxSeats: 50,
      waitlist: 0,
      bgColor: "bg-dev-dog-blue",
      borderColor: "border-dev-dog-blue",
      currentDay: "W",
      otherTimes: ["M", "11:25 am - 12:15 pm", "Math 210"],
    },
    {
      classTitle: "SPAN 1001",
      className: "Elementary Spanish I",
      description:
        "Interactive activities to practice conversation, vocabulary, and basic grammar.",
      locationLong: "Language Building 105",
      locationShort: "Lang 105",
      prereq: "",
      coreq: "",
      professor: "Prof. Carla Ruiz",
      semester: "Fall",
      timeStart: "3:00 pm",
      timeEnd: "3:50 pm",
      timeDifference: null,
      credits: 3,
      crn: 40103,
      openSeats: 30,
      maxSeats: 30,
      waitlist: 0,
      bgColor: "bg-lake-herrick",
      borderColor: "border-lake-herrick",
      currentDay: "MWF",
      otherTimes: ["", "", ""],
    },
  ],

  Thursday: [
    {
      classTitle: "BIOL 1200",
      className: "Principles of Biology",
      description:
        "Lab session focusing on microscopy, cell division, and basic genetics experiments.",
      locationLong: "Science Center 220",
      locationShort: "Sci 220",
      prereq: "BIOL 1200",
      coreq: "",
      professor: "Dr. Leslie Park",
      semester: "Fall",
      timeStart: "8:00 am",
      timeEnd: "9:15 am",
      timeDifference: null,
      credits: 1,
      crn: 40104,
      openSeats: 20,
      maxSeats: 20,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "TR",
      otherTimes: ["MWF", "9:10 am - 10:00 am", "Sci 110"],
    },
    {
      classTitle: "SPAN 1001",
      className: "Elementary Spanish I",
      description:
        "Cultural exploration of Spanish-speaking countries. Reading short texts and dialogues.",
      locationLong: "Language Building 105",
      locationShort: "Lang 105",
      prereq: "",
      coreq: "",
      professor: "Prof. Carla Ruiz",
      semester: "Fall",
      timeStart: "1:15 pm",
      timeEnd: "2:30 pm",
      timeDifference: null,
      credits: 3,
      crn: 40103,
      openSeats: 30,
      maxSeats: 30,
      waitlist: 0,
      bgColor: "bg-lake-herrick",
      borderColor: "border-lake-herrick",
      currentDay: "TR",
      otherTimes: ["MWF", "3:00 pm - 3:50 pm", "Lang 105"],
    },
  ],

  Friday: [
    {
      classTitle: "MATH 2250",
      className: "Calculus I",
      description:
        "Recap session on integrals and their applications; short quiz on differentiation.",
      locationLong: "Mathematics Building 210",
      locationShort: "Math 210",
      prereq: "",
      coreq: "",
      professor: "Dr. George Simons",
      semester: "Fall",
      timeStart: "11:25 am",
      timeEnd: "12:15 pm",
      timeDifference: null,
      credits: 4,
      crn: 40102,
      openSeats: 50,
      maxSeats: 50,
      waitlist: 0,
      bgColor: "bg-dev-dog-blue",
      borderColor: "border-dev-dog-blue",
      currentDay: "F",
      otherTimes: ["MW", "11:25 am - 12:15 pm", "Math 210"],
    },
  ],
};

const dummySchedule5: WeekScheduleType = {
  Monday: [
    {
      classTitle: "GEOL 1120",
      className: "Introduction to Earth Sciences",
      description:
        "Survey of geological processes, Earth materials, and plate tectonics.",
      locationLong: "Geology Building 200",
      locationShort: "Geol 200",
      prereq: "",
      coreq: "",
      professor: "Dr. Ian Caldwell",
      semester: "Spring",
      timeStart: "11:10 am",       // shifted to after 11:00 am
      timeEnd: "12:00 pm",
      timeDifference: null,
      credits: 3,
      crn: 50201,
      openSeats: 40,
      maxSeats: 40,
      waitlist: 0,
      bgColor: "bg-dev-dog-blue",
      borderColor: "border-dev-dog-blue",
      currentDay: "MW",            // same as original: appears Monday & Wednesday
      otherTimes: ["F", "11:10 am - 12:00 pm", "Geol 200"], // updated Friday time
    },
    {
      classTitle: "ANTH 2000",
      className: "Cultural Anthropology",
      description:
        "Study of human cultural variation and universals, including kinship, religion, and social organization.",
      locationLong: "Anthropology Hall 120",
      locationShort: "Anth 120",
      prereq: "",
      coreq: "",
      professor: "Dr. Maria Ortiz",
      semester: "Spring",
      timeStart: "1:20 pm",        // shifted to after 11:00 am
      timeEnd: "2:10 pm",
      timeDifference: null,
      credits: 3,
      crn: 50202,
      openSeats: 35,
      maxSeats: 35,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "M",             // Monday-only section
      otherTimes: ["W", "11:10 am - 12:00 pm", "Anth 120"], // updated Wed time
    },
    {
      classTitle: "LING 2100",
      className: "Introduction to Linguistics",
      description:
        "Overview of language structure, phonetics, morphology, syntax, and sociolinguistic variation.",
      locationLong: "Language & Linguistics 310",
      locationShort: "Ling 310",
      prereq: "",
      coreq: "",
      professor: "Dr. Anna Stevens",
      semester: "Spring",
      timeStart: "3:30 pm",        // shifted to after 11:00 am
      timeEnd: "4:20 pm",
      timeDifference: null,
      credits: 3,
      crn: 50203,
      openSeats: 40,
      maxSeats: 40,
      waitlist: 0,
      bgColor: "bg-lake-herrick",
      borderColor: "border-lake-herrick",
      currentDay: "MWF",           // appears Monday, Wednesday, Friday
      otherTimes: ["", "", ""],
    },
  ],

  Tuesday: [
    {
      classTitle: "ANTH 2000",
      className: "Cultural Anthropology",
      description:
        "Exploration of research methods, ethnographic fieldwork, and ethics in anthropology.",
      locationLong: "Anthropology Hall 120",
      locationShort: "Anth 120",
      prereq: "",
      coreq: "",
      professor: "Dr. Maria Ortiz",
      semester: "Spring",
      timeStart: "11:30 am",       // shifted to after 11:00 am
      timeEnd: "12:45 pm",
      timeDifference: null,
      credits: 3,
      crn: 50202,
      openSeats: 35,
      maxSeats: 35,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "TR",            // Tuesday/Thursday
      otherTimes: ["MW", "1:20 pm - 2:10 pm", "Anth 120"], // referencing M/W times
    },
  ],

  Wednesday: [
    {
      classTitle: "LING 2100",
      className: "Introduction to Linguistics",
      description:
        "In-depth look at language families, historical linguistics, and language contact phenomena.",
      locationLong: "Language & Linguistics 310",
      locationShort: "Ling 310",
      prereq: "",
      coreq: "",
      professor: "Dr. Anna Stevens",
      semester: "Spring",
      timeStart: "4:00 pm",        // shifted to after 11:00 am
      timeEnd: "4:50 pm",
      timeDifference: null,
      credits: 3,
      crn: 50203,
      openSeats: 40,
      maxSeats: 40,
      waitlist: 0,
      bgColor: "bg-lake-herrick",
      borderColor: "border-lake-herrick",
      currentDay: "MWF",
      otherTimes: ["", "", ""],
    },
  ],

  Thursday: [
    {
      classTitle: "GEOL 1120",
      className: "Introduction to Earth Sciences",
      description:
        "Lab session for mineral identification, map reading, and field observation methods.",
      locationLong: "Geology Lab 250",
      locationShort: "Geol Lab 250",
      prereq: "GEOL 1120",
      coreq: "",
      professor: "Dr. Ian Caldwell",
      semester: "Spring",
      timeStart: "11:30 am",       // shifted to after 11:00 am
      timeEnd: "12:45 pm",
      timeDifference: null,
      credits: 1,
      crn: 50204,
      openSeats: 20,
      maxSeats: 20,
      waitlist: 0,
      bgColor: "bg-dev-dog-blue",
      borderColor: "border-dev-dog-blue",
      currentDay: "TR",
      otherTimes: ["MW", "11:10 am - 12:00 pm", "Geol 200"],
    },
    {
      classTitle: "ANTH 2000",
      className: "Cultural Anthropology",
      description:
        "Review session on key ethnographies, plus a short quiz on cross-cultural perspectives.",
      locationLong: "Anthropology Hall 120",
      locationShort: "Anth 120",
      prereq: "",
      coreq: "",
      professor: "Dr. Maria Ortiz",
      semester: "Spring",
      timeStart: "1:20 pm",        // shifted to after 11:00 am
      timeEnd: "2:10 pm",
      timeDifference: null,
      credits: 3,
      crn: 50202,
      openSeats: 35,
      maxSeats: 35,
      waitlist: 0,
      bgColor: "bg-bulldog-red",
      borderColor: "border-bulldog-red",
      currentDay: "F",
      otherTimes: ["MW", "1:20 pm - 2:10 pm", "Anth 120"],
    },
  ],

  Friday: [
    {
      classTitle: "GEOL 1120",
      className: "Introduction to Earth Sciences",
      description:
        "Short quiz on weekly topics and discussion of Earth’s surface processes.",
      locationLong: "Geology Building 200",
      locationShort: "Geol 200",
      prereq: "",
      coreq: "",
      professor: "Dr. Ian Caldwell",
      semester: "Spring",
      timeStart: "11:10 am",       // shifted to after 11:00 am
      timeEnd: "12:00 pm",
      timeDifference: null,
      credits: 3,
      crn: 50201,
      openSeats: 40,
      maxSeats: 40,
      waitlist: 0,
      bgColor: "bg-dev-dog-blue",
      borderColor: "border-dev-dog-blue",
      currentDay: "MW",            // appears M/W but also has a Friday session
      otherTimes: ["MW", "11:10 am - 12:00 pm", "Geol 200"],
    },
    {
      classTitle: "LING 2100",
      className: "Introduction to Linguistics",
      description:
        "Advanced phonetic transcription exercises and morphological problem sets.",
      locationLong: "Language & Linguistics 310",
      locationShort: "Ling 310",
      prereq: "",
      coreq: "",
      professor: "Dr. Anna Stevens",
      semester: "Spring",
      timeStart: "2:00 pm",        // shifted to after 11:00 am
      timeEnd: "3:15 pm",
      timeDifference: null,
      credits: 3,
      crn: 50203,
      openSeats: 40,
      maxSeats: 40,
      waitlist: 0,
      bgColor: "bg-lake-herrick",
      borderColor: "border-lake-herrick",
      currentDay: "TR",
      otherTimes: ["MWF", "4:00 pm - 4:50 pm", "Ling 310"],
    },
  ],
};



// Handles retrieval of saved plans from local storage and displays a list of them for the user to select
export default function SavedPlans() {
  // Parameters for a saved plan
  interface SavedPlanType {
    title: string;
    data: WeekScheduleType;
  }

  const [savedPlans, setSavedPlans] = useState<SavedPlanType[]>([]);
  const [planToDelete, setPlanToDelete] = useState<string | null>(null);

  useEffect(() => {
    try {
      // REPLACE WITH RETRIEVAL OF REAL DATA WHEN POSSIBLE
      // Save the dummy schedules to browser local storage
      console.log("Saving to local storage"); // for debugging
      localStorage.setItem("Schedule 1", JSON.stringify(dummySchedule));
      localStorage.setItem("Schedule 2", JSON.stringify(dummySchedule2));
      localStorage.setItem("Schedule 3", JSON.stringify(dummySchedule3));
      localStorage.setItem("Schedule 4", JSON.stringify(dummySchedule4));
      localStorage.setItem("Schedule 5", JSON.stringify(dummySchedule5));
      console.log("Schedules saved"); // for debugging

      // Retrieve schedules from local storage and populate the plans array
      const plans = [];
      // Loop through local storage
      for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        // Retrieve key for local storage element
        if (key) {
          // Retrieve data matching key
          const data = localStorage.getItem(key);
          // Only proceed if the data looks like a WeekSchedule component
          if (data?.startsWith('{"Monday"')) {
            // Parse the data from the JSON
            plans.push({
              title: key,
              data: JSON.parse(data) as WeekScheduleType,
            });
          }
        }
      }
      // Sort plans by title, because apparently the browser can't be bothered to keep the order straight
      plans.sort((a, b) => a.title.localeCompare(b.title));
      setSavedPlans(plans);
    } catch (error) {
      // If something goes wrong, this message should be displayed in the browser console
      console.error("Failed to parse local storage data: ", error);
    }
  }, []);

  const confirmDeletePlan = (title: string) => {
    setPlanToDelete(title);
  };

  const deletePlan = () => {
    if (planToDelete) {
      localStorage.removeItem(planToDelete);
      setSavedPlans((prevPlans) =>
        prevPlans.filter((plan) => plan.title !== planToDelete),
      );
      setPlanToDelete(null);
    }
  };

  const cancelDelete = () => {
    setPlanToDelete(null);
  };

  return (
    <div className="min-h-screen">
      <Navbar />

      <div className="z-1 mb-10 ml-auto mr-auto mt-20 flex h-[85vh] w-4/5 flex-col flex-nowrap items-center overflow-y-auto rounded-xl border-2 border-black bg-barely-pink">
        {savedPlans.map((plan, index) => (
          <SavedPlan
            key={index}
            planTitle={plan.title}
            plan={plan.data}
            onDelete={() => confirmDeletePlan(plan.title)}
          />
        ))}
      </div>
      {planToDelete && (
        <DeletePlan
          onConfirm={deletePlan}
          onCancel={cancelDelete}
          planTitle={planToDelete}
        />
      )}
    </div>
  );
}
